name: Android Build

on:
  push:
    branches:
      - main  # Or any branch you prefer

jobs:
  build:
    name: Build APK
    runs-on: self-hosted 

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: test storage
        run: df -h 

      - name: test docker
        run: docker ps
